INSERT INTO burgers (burger_name, devoured)
VALUES
("Hobbitses Burger", false),
("50 Cent Burger", false),
("Angus", true),
("Bacon Cheeseburger", true),
("Cheeseburger", true),
("Chili Burger", false),
("Barbecue Burger", false),
("Hawaii Burger", true),
("Slider", false),
("Australasian Burger", false),
('Bøfsandwich', true),
('Butter burger', false),
("Buffalo Burger", false),
("Carolina Burger", true),
("Curry Burger", false),
("Green Chile Burger", false),
("Hamdog", false),
("Jucy Lucy", false),
("Luther Burger", false),
("Rice Burger", false),
("Salmon Burger", false),
("50/50 Burger", false),
("Kimchi Burger", false),
("Luther Burger", false),
("Steamed Cheeseburger", false),
("Umami Burger", true),
("Slugburger", false),
("Slopper", false);
